# This rule is not used by the project arbiter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over project-arbiter.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arbiter
    app.kubernetes.io/managed-by: kustomize
  name: project-admin-role
rules:
- apiGroups:
  - project-arbiter.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - project-arbiter.io
  resources:
  - projects/status
  verbs:
  - get
