# This rule is not used by the project arbiter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the platform.upsidedown.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arbiter
    app.kubernetes.io/managed-by: kustomize
  name: tenantnamespace-editor-role
rules:
- apiGroups:
  - platform.upsidedown.io
  resources:
  - tenantnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.upsidedown.io
  resources:
  - tenantnamespaces/status
  verbs:
  - get
