# This rule is not used by the project arbiter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.upsidedown.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: arbiter
    app.kubernetes.io/managed-by: kustomize
  name: tenantnamespace-viewer-role
rules:
- apiGroups:
  - platform.upsidedown.io
  resources:
  - tenantnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.upsidedown.io
  resources:
  - tenantnamespaces/status
  verbs:
  - get
