apiVersion: project-arbiter.io/v1alpha1
kind: Settler
metadata:
  name: starcourt
spec:
  settlerID: starcourt
  # targetNamespace: settler-starcourt   # optional; defaults to settler-<settlerID>
  # targetNamespaces:             # optional; defaults to ["settler-<settlerID>"]
  #   - starcourt-mall
  #   - starcourt-ops
  # adminSubjects: []             # optional
  # baselinePolicy: {}           # optional
