apiVersion: project-arbiter.io/v1alpha1
kind: Project
metadata:
  name: starcourt
spec:
  projectID: starcourt
  # targetNamespace: project-starcourt   # optional; defaults to project-<projectID>
  # targetNamespaces:             # optional; defaults to ["project-<projectID>"]
  #   - starcourt-mall
  #   - starcourt-ops
  # adminSubjects: []             # optional
  # baselinePolicy: {}           # optional
